version: '3'

services:
  dockertest:
    image: webmvc
    build:
      context: .
      dockerfile: dockerTest/Dockerfile
    depends_on:
      - webapi1
      - webapi2
      - sql.data
      - rabbitmq

  webapi1:
    image: webapi1
    build:
      context: .
      dockerfile: webApi1/Dockerfile
    depends_on:
      - sql.data
      - rabbitmq

  webapi2:
    image: webapi2
    build:
      context: .
      dockerfile: webApi2/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq

  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  nosql.data:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"